### ISSUE TITLE
モジュール対応に伴ってDEDAの一部機械レシピが紐づけが切れている

### ISSUE THREAD

**Issue by tier940** [GTModpackTeam/GTExpert-Core#222]
- Draconic Equipment Tier-Up / Draconic Equipment Upgrades
    - JEIのカテゴリには居るが機械(Draconic Fusion Crafter)と紐付いていない(Uキーで確認するやつ)

**Comment by MrKono** [comment]
Auto Chiselはレシピ数が膨大なため、前からJEIカテゴリには表示されません。
https://github.com/GTModpackTeam/GTExpert-Core/blob/27c63fcbb4b5cff33bca3e2b74c1bc7008ec7ced/src/main/java/gtexpert/integration/chisel/ChiselModule.java#L46
